name: test

on: [push]

jobs:
    test:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2

            - name: Dependencies
              run: sudo apt update && sudo apt install xorg-dev

            - name: Build
              run: make build

            - name: Test
              run: make run-tests
